### ISSUE TITLE
Cannot save from downloaded site

### ISSUE THREAD

**Issue by professionalPeter** [simonbaird/tiddlyhost#175] opened 2021-08-22 22:24 UTC
Creating a site, downloading it and immediately trying to save does not appear to work. I've followed the directions linked below, but have not been able to get any changes to save back to TiddlyHost from a downloaded file.

Saving configuration instructions: https://github.com/simonbaird/tiddlyhost/wiki/TiddlySpot-Saver-configuration-for-Tiddlyhost-and-Tiddlyspot

### Repro steps
1. Create site by entering a name and checking private
2. Download the newly created site (e.g. foo.tiddlyhost.com)
3. Open downloaded file in browser
4. Create and save new tiddler
5. Click Save Wiki button in the sidebar
6. Enter URL (e.g. https://foo.tiddlyhost.com) to newly created site in "Server URL" input box under Control Panel | Saving | TiddlySpot Saver
7. Click Save Wiki button in the sidebar
8. Visit newly created site in browser
9. Open the "All" tab

### Expected Results
The new tiddler should be listed in the All tab

### Observed Results
It's not there and appears that the downloaded file was never able to upload

**Comment by simonbaird** [comment] 2021-08-23 13:58
You can't save directly to Tiddlyhost from a locally downloaded site, so I think you're describing expected behaviour. (It's because web browsers' security policies don't allow it.)

But you can manually upload the locally modified site by using the "Upload" option from the "Actions" menu at https://tiddlyhost.com/sites .

**Comment by professionalPeter** [comment] 2021-08-24 03:25
Aha, yes I did misunderstand the designed behavior. Am I right in thinking this limitation applies to Tiddly Desktop as well?

Thanks for the clarification

**Comment by simonbaird** [comment] 2021-09-07 17:30
I don't know about Tiddly Desktop, sorry.

**Comment by simonbaird** [comment] 2021-09-07 17:31
Let's close this issue.

**Closed by simonbaird** 2021-09-07 17:31 UTC
