### ISSUE TITLE
Wiki not Saving since 07th September

### ISSUE THREAD

**Issue by nicolekaro-admin** [simonbaird/tiddlyhost#244] opened 2022-09-09 06:37 UTC
Hello!

I made a few changes (manor changes) in my Wiki on 07th Sept. and yesterday.
I always pushed the save button and it told me it was saved. 

But yesterday I opened up my wiki and my changes from 07th Sep were not saved - ok, I thought, maybe I forgot to save and it was not a big issue for me yesterday. I made sure that I always saved it via the save button then but today my changes are all gone again! 

Before that it always saved my changes properly. I did not change any Settings regarding the saving. So what happened? Why does my Wiki not save anymore?? I always were logged in to the host mainpage...

Can you please give me a fix for that? 
For now I will not use your side for writing my wikis because I'm not sure if it's saving.

greetings!

**Comment by nicolekaro-admin** [comment] 2022-09-09 06:43
OK, I checked again - yesterday one change in one of my wikis was saved. So I can tell it seems that tiddlyhost logged me out and therefore were not able to save my wiki.
Can you tell me when I get auto logedout? After which time? And is it possible to deactivate it or maybe to make an alert while saving the wiki so that it tells me that it cannot be saved because of logged out account???

**Comment by simonbaird** [comment] 2022-09-09 21:30
Hi, thanks for the report about your bad experience with saving.

The best way to avoid this is to look for the "Saved wiki" confirmation message. When you click the save button there should be two notification messages (usually in the top right). The first one is "Starting to save wiki" and the second one is "Saved wiki". If you make sure the "Saved wiki" notification appears then you can generally be sure your save was successful. Conversely if you don't see it, then it's likely the save didn't succeed. In that case you could confirm that you're still logged in, or maybe wait a little while and try again in case the server was restarting or had some kind of temporary problem.

That said, there is a possibilty you're encountering a different problem and some more investigation is needed. Would you say the "Saved wiki" confirmation message showed up each time? Would be interested in trying again to save some changes and let me know if the problem is happening repeatedly?

**Comment by simonbaird** [comment] 2022-09-24 21:30
FWIW I think it's likely you were impacted by #245, which should now be fixed.

**Comment by simonbaird** [comment] 2022-11-25 04:09
I'll close the issue now since I think the problem is solved, but I want to apologize for causing you to lose some data, and to say thanks very much for reporting this. Your report helped me realize that Tiddlyhost did have a serious bug (#245 ) that could sometimes cause people to lose their changes the way you did.

**Closed by simonbaird** 2022-11-25 04:09 UTC
