### ISSUE TITLE
TH down?

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#91] opened 2021-03-11 22:49 UTC
Can't access TH for the past 20 minutes, possibly more.

**Comment by simonbaird** [comment] 2021-03-11 22:53
I just noticed it too. I can't ping. Trying a restart of the dreamcompute instance.

**Comment by simonbaird** [comment] 2021-03-11 22:54
Looks like we're back online now.

**Comment by simonbaird** [comment] 2021-03-11 22:54
Thanks for the report.

**Comment by simonbaird** [comment] 2021-03-11 23:01
I briefly looking in the logs but didn't find much. Would be good to know more about the root cause, but anyway I'll close this.

**Comment by simonbaird** [comment] 2021-03-11 23:01
I did find #92 though, but probably not related to the outage.

**Closed by simonbaird** 2021-03-11 23:01 UTC
Labels: ticket

**Comment by simonbaird** [comment] 2021-03-11 23:02
No outage notices at https://www.dreamhoststatus.com/ this time.

**Comment by twMat** [comment] 2021-03-11 23:15
Thanks.
