### ISSUE TITLE
some sites not downloading via tiddlyhost "Your sites" panel

### ISSUE THREAD

**Issue by springerspandrel** [simonbaird/tiddlyhost#190] opened 2021-10-29 17:11 UTC
Using the Actions menu at right, choosing download results in nothing (brief sign of activity at favicon, then aborted) for ethicsatwes.tiddlyspot.com

Other sites of mine download properly from the same interface.

I'll export all my tiddlers for backup purposes, but perhaps someone can troubleshoot what interferes with saving from that panel. Thx!

**Comment by simonbaird** [comment] 2021-11-03 22:14
I couldn't reproduce this. Are you still having the same problem?

**Comment by simonbaird** [comment] 2021-11-03 22:22
Actually disregard the above, I can reproduce it. It's weird since the same url, i.e. http://<site>.tiddlyspot.com/download appears to work fine in another tab, but it fails when clicking it from the actions menu. Thanks for the report. I'll investigate further.

**Comment by simonbaird** [comment] 2021-11-04 04:46
Not sure, but it's possibly related to it being a http link in an otherwise https page. Fix coming soon.

**Comment by simonbaird** [comment] 2021-11-04 06:46
Should be fixed now.

**Closed by simonbaird** 2021-11-04 06:46 UTC
