### ISSUE TITLE
View count gets reset after uploading.

### ISSUE THREAD

**Issue by Marxsal** [simonbaird/tiddlyhost#277] opened 2022-12-02 17:06 UTC
I don't know if this is a bug or a feature, but it appears that view count gets reset after uploading. In most cases, the TW being uploaded is the same as the original. It probably was downloaded for purposes of upgrading or data-loading, which would have been slow if performed online.

**Comment by simonbaird** [comment] 2022-12-03 22:55
I can't reproduce this behavior. As far as I can tell the view count is not reset when uploading new content to a site. Are you able to reproduce this reliably? Could you walk me through your proceedure?

One note: The "view count" doesn't increment when you're logged in and looking at your own site. For that reason, a private site is likely to have zero views always. Only a public site can have a view count above zero. (There is also an "access count" that does record your own views, but currently that is not visible.)

**Comment by simonbaird** [comment] 2023-01-31 16:54
Closing this now, but please reopen if needed.

**Closed by simonbaird** 2023-01-31 16:54 UTC
Labels: needsinfo
